Repository CODING-TEST-ANYMORE/Coding-Test-Study, pull requests merged in 2023-05, with the labels that each got.

#27 [WEEK3] Heap - 유진
  03-Heap/eugene/2075_N번째수.py
  03-Heap/eugene/과일장수.py
  03-Heap/eugene/기사단원의무기.py
  03-Heap/eugene/더맵게.py
  03-Heap/eugene/햄버거만들기.py
Labels: python

#21 [Week 3] Heap - 하은
  03-Heap/haeun/백준_N번째 큰 수.cpp
  03-Heap/haeun/백준_쇠막대기.cpp
  03-Heap/haeun/백준_이중 우선순위 큐.cpp
  03-Heap/haeun/프로그래머스_다리를 지나는 트럭.cpp
  03-Heap/haeun/프로그래머스_더맵게.cpp
  03-Heap/haeun/프로그래머스_디스크 컨트롤러.cpp
Labels: c++

#31 [Week 3] Heap - 지원
  .DS_Store
  03-Heap/.DS_Store
  03-Heap/jiwon/11723_집합.cp
  03-Heap/jiwon/2075_N번째 큰 수.cp
  03-Heap/jiwon/2447_별찍기-10.cp
  03-Heap/jiwon/5635_생일.cp
  03-Heap/jiwon/7662_이중 우선순위 큐.cp
  03-Heap/jiwon/더 맵게.cp
Labels: c++

#30 [Week 3] Heap - 주영
  03-Heap/jooyoung/2075_N번째 큰.py
  03-Heap/jooyoung/7662_이중 우선순위 큐.py
  03-Heap/jooyoung/더 맵게.py
Labels: python

#26 [Week3] Heap - 선희
  03-Heap/Sunny/n번째 큰수.java
  03-Heap/Sunny/괄호변환.java
  03-Heap/Sunny/더맵게.java
  03-Heap/Sunny/문자열압축.java
  03-Heap/Sunny/소수찾기.java
  03-Heap/Sunny/이중 우선순위 큐.java
Labels: java

#25 [Week3] Heap - 채린
  03-Heap/chaerin/2075_N번째큰수.py
  03-Heap/chaerin/test1.py
  03-Heap/chaerin/test2.py
  03-Heap/chaerin/test3.py
  03-Heap/chaerin/test4.py
  03-Heap/chaerin/test5.py
Labels: python

#23 [Week 3] Heap - 용택
  03-Heap/yongtaek/N번째큰수.java
  03-Heap/yongtaek/더맵게.java
  03-Heap/yongtaek/이중우선순위큐.java
  03-Heap/yongtaek/절대값힙.java
  03-Heap/yongtaek/최대힙.java
  03-Heap/yongtaek/최소힙.java
Labels: java

#33 [Week 3] Heap - 재훈
  03-Heap/jaehoon/11279_최대힙.cpp
  03-Heap/jaehoon/11286_절대값힙.cpp
  03-Heap/jaehoon/1931_회의실 배정.cpp
  03-Heap/jaehoon/2075_N번째큰수.cpp
  03-Heap/jaehoon/7662_이중우선순위큐.cpp
  03-Heap/jaehoon/README.md
  03-Heap/jaehoon/더맵게.cpp
Labels: c++

#41 [Week4] DFS&BFS - 주영
  04-DFS&BFS/jooyoung/1260_DFS와BFS.py
  04-DFS&BFS/jooyoung/16236_아기상어.py
  04-DFS&BFS/jooyoung/1697_숨바꼭질.py
  04-DFS&BFS/jooyoung/sw_1954.py
Labels: python

#40 [Week 4] BFS&DFS-채린
  04-DFS&BFS/chaerin/1012_유기농배추.py
  04-DFS&BFS/chaerin/1260_DFS와BFS.py
  04-DFS&BFS/chaerin/162356_아기상어.py
  04-DFS&BFS/chaerin/1697_숨바꼭질.py
Labels: python

#34 [Week 4] DFS&BFS - 지원
  .DS_Store
  03-Heap/jiwon/더 맵게.cp
  04-DFS&BFS/.DS_Store
  04-DFS&BFS/jiwon/.DS_Store
  04-DFS&BFS/jiwon/1260_DFS와 BFS.cp
  04-DFS&BFS/jiwon/13549_숨바꼭질3.cp
  04-DFS&BFS/jiwon/13913_숨바꼭질4.cp
  04-DFS&BFS/jiwon/1697_숨바꼭질.cp
Labels: c++

#39 [Week 4] DFS&BFS - 하은
  04-DFS&BFS/haeun/백준_DFS_BFS.cpp
  04-DFS&BFS/haeun/백준_숨바꼭질.cpp
  04-DFS&BFS/haeun/백준_아기상어.cpp
  04-DFS&BFS/haeun/프로그래머스_단어 변환.cpp
Labels: c++

#38 [Week 4] DFS&BFS -지연
  04-DFS&BFS/jiyeon/1260_DFS와BFS
  04-DFS&BFS/jiyeon/16236_아기상어
  04-DFS&BFS/jiyeon/1697_숨바꼭질
  04-DFS&BFS/jiyeon/9461_파도반수열
Labels: python

#37 [Week4] DFS & BFS -수경
  04-DFS&BFS/sookyung/DFS와BFS.py
  04-DFS&BFS/sookyung/반복수열.py
  04-DFS&BFS/sookyung/숨바꼭질.py
  04-DFS&BFS/sookyung/아기상어.py
  05-BruteForce/sookyung/1,2,3더하기.py
  05-BruteForce/sookyung/다음순열.py
  05-BruteForce/sookyung/분해합.py
  05-BruteForce/sookyung/영화감독숌.py
Labels: python

#43 [Week 4] DFS & BFS - 하윤
  04-DFS&BFS/hayoun/백준1260.cpp
  04-DFS&BFS/hayoun/백준14503.cpp
  04-DFS&BFS/hayoun/백준16236.cpp
  04-DFS&BFS/hayoun/백준1697.cpp
Labels: c++

#42 [Week4] DFS & BFS - 용택
  04-DFS&BFS/yongtaek/DFS와BFS.java
  04-DFS&BFS/yongtaek/숨바꼭질.java
  04-DFS&BFS/yongtaek/아기상어.java
  04-DFS&BFS/yongtaek/토마토.java
Labels: java

#35 [Week 4] DFS&BFS - 선희
  04-DFS&BFS/Sunny/2개 이하로 다른 비트.java
  04-DFS&BFS/Sunny/DFS와 BFS.java
  04-DFS&BFS/Sunny/숨바꼭질.java
  04-DFS&BFS/Sunny/아기상어.java
Labels: java

#45 [WEEK4] DFS&BFS - 유진
  04-DFS&BFS/1260_DFS와BFS.py
  04-DFS&BFS/1697_숨바꼭질.py
  04-DFS&BFS/소수찾기.py
Labels: python

#44 [Week 4] DFS & BFS - 재훈
  04-DFS&BFS/1260_DFS와BFS.cpp
  04-DFS&BFS/1697_숨바꼭질.cpp
  04-DFS&BFS/18185_라면사기.cpp
Labels: c++

#51 [Week 5] Brute Force - 지연
  05-BruteForce/jiyeon/10655_마라톤1
  05-BruteForce/jiyeon/10972_다음순열
  05-BruteForce/jiyeon/1189_컴백홈
  05-BruteForce/jiyeon/9095_1,2,3더하기
Labels: python

#57 [Week 5] Brute Force -수경
  05-BruteForce/sookyung/1,2,3더하기.py
  05-BruteForce/sookyung/다음순열.py
  05-BruteForce/sookyung/분해합.py
  05-BruteForce/sookyung/영화감독숌.py
Labels: python

#49 [Week 5] Brute Force - 선희
  05-BruteForce/Sunny/1, 2, 3 더하기.java
  05-BruteForce/Sunny/다음 순열.java
  05-BruteForce/Sunny/숫자의 표현.java
  05-BruteForce/Sunny/연산자 끼워넣기.java
Labels: java

#53 [Week 5] BruteForce - 주영
  05-BruteForce/jooyoung/10972_다음순열.py
  05-BruteForce/jooyoung/9095_1 2 3더하기.py
  05-BruteForce/jooyoung/스택큐_같은 숫자는 싫어.py
  05-BruteForce/jooyoung/하샤드 수.py
Labels: python

#52 [Week 5] BruteForce - 하은
  05-BruteForce/haeun/10972_다음 순열.cpp
  05-BruteForce/haeun/1969_DNA.cpp
  05-BruteForce/haeun/9095_1, 2, 3 더하기.md
Labels: c++

#55 [Week5] Brute Force - 용택
  05-BruteForce/yongtaek/다음순열.java
  05-BruteForce/yongtaek/더하기.java
  05-BruteForce/yongtaek/체스판다시칠하기.java
Labels: java

#56 [Week5] Brute Force - 재훈
  05-BruteForce/10972_다음순열.cpp
  05-BruteForce/11000_강의실배정.cpp
  05-BruteForce/20365_블로그2.cpp
  05-BruteForce/9095_1,2,3더하기.cpp
  06-DP/10808_알파벳 개수.cpp
  06-DP/1463.cpp
  06-DP/1520_내리막길.cpp
  06-DP/2979_트럭주차.cpp
Labels: c++

#46 [WEEK5] BruteForce - 지원
  .DS_Store
  05-BruteForce/.DS_Store
  05-BruteForce/jiwon/1012_유기농 배추.cp
  05-BruteForce/jiwon/10972_다음 순열.cp
  05-BruteForce/jiwon/2178_미로탐색.cp
  05-BruteForce/jiwon/9095_1,2,3 더하기.cp
Labels: c++

#50 [Week 5] Brute Force - 하윤
  05-BruteForce/hayoun/백준10972.cpp
  05-BruteForce/hayoun/백준9019.cpp
  05-BruteForce/hayoun/백준9095.cpp
  05-BruteForce/hayoun/키패드누르기.cpp
Labels: c++

#54 [Week 5] BruteForce - 유진
  05-BruteForce/Eugene/1520_내리막길.py
  05-BruteForce/Eugene/9095_123더하기.py
  05-BruteForce/Eugene/프로그래머스_문자열 압축.py
Labels: python

#58 [Week6] DP - 선희
  06-DP/Sunny/1로 만들기.java
  06-DP/Sunny/귤 고르기.java
  06-DP/Sunny/기능개발.java
  06-DP/Sunny/내리막길.java
Labels: java

#59 [Week 6] DP -수경
  06-DP/sookyung/1로만들기.py
  06-DP/sookyung/계단오르기.py
  06-DP/sookyung/내리막길.py
  06-DP/sookyung/퇴사.py
Labels: python

#60 [Week 6] DP - 지연
  06-DP/jiyeon/10825_국영수
  06-DP/jiyeon/1157_단어공부
  06-DP/jiyeon/1463_1로만들기
  07-Greedy/jiyeon/11724_연결요소의개수
  07-Greedy/jiyeon/17828_문자열화폐
  07-Greedy/jiyeon/1789_수들의합
  07-Greedy/jiyeon/2579_계단오르기
Labels: python

#62 [Week 6] DP - 용택
  06-DP/yongtaek/RGB거리.java
  06-DP/yongtaek/내리막길.java
  06-DP/yongtaek/연속합.java
  06-DP/yongtaek/일로만들기.java
Labels: java

#61 [Week 6] DP - 하은
  06-DP/haeun/1149_RGB 거리.cpp
  06-DP/haeun/1463_1로 만들기.md
  06-DP/haeun/1520_내리막길.cpp
  06-DP/haeun/2579_계단 오르기.cpp
Labels: c++

#63 [week 6] DP - 주영
  06-DP/jooyoung/1463_1로 만들기.py
  06-DP/jooyoung/1520_내리막길.py
  06-DP/jooyoung/완전탐색_최소직사각형.py
  06-DP/jooyoung/정렬_k번째수.py
Labels: python

#64 [week 6] DP - 재훈
  06-DP/jaehoon/10808_알파벳 개수.cpp
  06-DP/jaehoon/1463.cpp
  06-DP/jaehoon/1520_내리막길.cpp
  06-DP/jaehoon/2979_트럭주차.cpp
Labels: c++

#72 [Week7] Greedy - 하은
  07-Greedy/haeun/17828_문자열 화폐.cpp
  07-Greedy/haeun/1789_수들의 합.cpp
Labels: c++
